[package]
name = "ezRest_cli"
version = "0.1.0"
authors = ["scrummer123 <simonpeters05@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
shellwords = "1.1.0"

[[bin]]
name = "ezrest"
path = "src/main.rs"